### ISSUE TITLE
buildevents adds extra "" to commands being passed to bash -c

### ISSUE THREAD

**Issue by lizthegrey** [honeycombio/buildevents#11]
This means that passing pipeline e.g. find | xargs will fail because there is no way to avoid wrapping the \| in quotes, causing it to be interpreted as an argument ("|") to find rather than a shell pipe. And passing the entire "find | xargs" command as $6 doesn't work because then bash sees it wrapped in "" and tries to execute the command names "find|xargs".

**Comment by maplebed** [comment]
Fixing this issue will require understanding:
• how circle yml interprets quotes
• to understand how they’ll pass quotes to `go`
• to understand how it’ll pass quotes to `exec`
• to understand how it’ll pass quotes to `bash`
• to understand how the command will be invoked

💯 should be fixed, and anybody who does, please write a blog post on the path towards victory.

**Comment by mx00s** [comment]
> * how circle yml interprets quotes

And presumably all the other `BUILDEVENT_CIPROVIDER`s, right?

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
