### ISSUE TITLE
Get SpanID within step

### ISSUE THREAD

**Issue by dmathieu** [honeycombio/buildevents#154]
**Is your feature request related to a problem? Please describe.**

I am using [go-test-trace](https://github.com/rakyll/go-test-trace), and would like to integrate it with buildevents.
The plugin provides me with a TraceID, but not seemingly not a SpanID. It would be nice to have that provided, so I could rebuild the `traceparent` supported by that plugin.

**Describe the solution you'd like**

I would like to be able to run `go-test-trace -traceparent=00-$TRACE_ID-$SPAN_ID-01` so my traces from both tools share the same context.

**Describe alternatives you've considered**

**Additional context**

**Comment by kentquirk** [comment]
Can you clarify, please, what you mean by "plugin" in this context? Buildevents puts what it "BUILD_ID" into trace_id and what it calls "STEP_ID" into the span_id. You're expected to supply both of those on the command line. Since honeycomb doesn't put any constraints on them (you're free to use "my_build_id" as a trace_id) there's not a generator built in. 

If you want to generate random trace IDs in hex as part of your build step, you might consider using jot. A command like `jot -r -w "%x" 1 0 4294967295` will generate an 8-digit random hex value; you can call this multiple times to build up a longer ID.

If that's not what you need, can you please clarify further?

**Comment by dmathieu** [comment]
Ah, I figured STEP_ID was something different. If it's the span ID, that's what I need then. Thank you.
