### ISSUE TITLE
add ability to use before/after invocations to wrap a `cmd`

### ISSUE THREAD

**Issue by maplebed** [honeycombio/buildevents#35]
It's lovely to pass an executable as an argument to `buildevents` and have it automatically time it. There are conditions during which that is not easy, and it'd be nice to have a syntax where you can run a wrap-setup command before and wrap-finish command after and still produce a `cmd` span. 

example: in jenkinsx yml, you can override steps in a buildpack with extra things to do before and after that step. Using these you can wrap existing buildpacks with extra functionality without changing the buildpack itself. Using the current buildevents paradigm, you can use a `step` command to do each of those by recording the timestamp before and then using that timestamp after, but that restricts the build trace to `build` and `step` - there's no way to use `cmd` and get yourself 3 levels of hierarchy.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
