### ISSUE TITLE
[CircleCI] `watch` aborts on job failure, underreporting workflow duration

### ISSUE THREAD

**Issue by symbiont-jacob-romer** [honeycombio/buildevents#48]
Apparently when `buildevents watch` encounters a failed job, it finishes the root span of the workflow run prematurely while other jobs are still running.

This leads to undercounting the workflow duration.

![img-2019-10-03-135238](https://user-images.githubusercontent.com/50886093/66151599-acbf4b00-e5e5-11e9-9d7a-ca42fb4f060c.png)

Log output from `buildevents watch $CIRCLE_WORKFLOW_ID`:
```
Oct  3 17:22:53.785: polling for jobs: 3 blocked, 1 failed, 2 running, 26 success
Oct  3 17:22:58.785: polling for jobs: 3 blocked, 1 failed, 1 running, 27 success
Build failed!
https://ui.honeycomb.io/sym-bee-ont/datasets/buildevents/trace?trace_id=d7bb7e39-5d6a-4afe-9900-a42bd71df865&trace_start_ts=1570121965&trace_end_ts=1570123979
```
In this workflow, the remaining blocked jobs actually ran to completion, but the root spans duration does not reflect that.

**Comment by maplebed** [comment]
Ooh, interesting. Would it be an accurate restatement of the current situation that `watch` records "duration until you know the build has failed" rather than "duration until the build stops running"?

(It's my understanding that once a single job fails, the build has failed, regardless of what else is currently in flight.)

**Comment by symbiont-jacob-romer** [comment]
> Ooh, interesting. Would it be an accurate restatement of the current situation that `watch` records "duration until you know the build has failed" rather than "duration until the build stops running"?

Exactly!

> (It's my understanding that once a single job fails, the build has failed, regardless of what else is currently in flight.)

Yep, that's correct.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
