### ISSUE TITLE
[CircleCI] Update data structures to reflect changed keys in Job object

### ISSUE THREAD

**Issue by maplebed** [honeycombio/buildevents#52]
https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md

The key names in the Job object changed. Update to use the new key names.

Note that this likely needs to happen in https://github.com/maplebed/go-circleci and then this project updated to use the newer library.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
