### ISSUE TITLE
[CircleCI] watch job takes too long on successful build

### ISSUE THREAD

**Issue by maplebed** [honeycombio/buildevents#54]
The watch job will (correctly) poll to ensure a failed build isn't going to start any more jobs. But when the watch job is the only job left, that means the build is finished, since there are no more jobs available to run. In that case it should exit immediately instead of polling, allowing the build to finish quickly.  In the current state the watch job extends the time it takes to build by an additional few minutes on every successful build and that's annoying.

The watch job should be updated to know _why_ it thinks the build is finished and gain some subtlety on when it should accept that it really is and when it should distrust the finished state and poll.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
