### ISSUE TITLE
buildevents cmd may result in leaking sensitive information

### ISSUE THREAD

**Issue by KristapsT** [honeycombio/buildevents#60]
Hey, sometimes variables are passed to CI commands that may contain sensitive information such as passwords, this makes it impossible to record those CI events with buildevents cmd since it would result in sending expanded variables with secrets to Honeycomb.

A couple of options how to try to solve it:
1. Record cmd attribute before parameters are expanded - not sure if this possible since buildevents would already receive an expanded bash command.

2. Provide an optional parameter to buildevents cmd that would allow to override or disable the cmd attribute.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
