### ISSUE TITLE
Buildevent API key failure is vague

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/buildevents#92]
When setting up buildevents, if the `BUILDEVENT_APIHOST` environment variable has JUST a hostname, and not a scheme + hostname, the failure message is "unable to verify API key" which is misleading.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
